### ISSUE TITLE
Consider flag to force export of dfns in legacy specs

### ISSUE THREAD

**Issue by tidoust** [w3c/reffy#1115]
Via https://github.com/w3c/browser-specs/pull/775

Old specs don't follow the data model for definitions that more recent specifications have adopted and don't have `data-export` attributes in particular. Definitions do get extracted but as internal definitions and are thus not available for cross-referencing purpose. It would be useful to be able to flag the spec as being a "legacy" spec with respect to definitions, and have the crawler export definitions of such legacy specs by default.

Not sure whether the mode should be a generic "legacy" mode or rather something a more specific "force export dfns" flag, which would be provide a more future-proof mechanism (today's "new" specs are tomorrow's "legacy" ones).

**Comment by dontcallmedom** [comment]
closed via #1120
