### ISSUE TITLE
Legacy dfn import marks all definitions as informative

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/reffy#1131]
Documents that aren't using the conventions of the dfn contract are also unlikely to use the convention to mark sections as informative or not. When they're processed by the dfn extractor, all definitions end up marked up as informative, which (for better or for worse) means they'll get flagged by ReSpec when used in a normative section (as discussed in https://github.com/w3c/respec/issues/4295)

That in particular applies to the RDF Concept definitions, making them harder to re-use directly in rdf-canon

**Comment by tidoust** [comment]
I may be missing something but the RDF Concept spec does use `informative` classes. Typically, the [Introduction](https://www.w3.org/TR/rdf11-concepts/#section-Introduction) section has a `class="informative"` attribute and the definitions it contains are thus indeed flagged as `informative`. That's not the case for definitions in other sections, e.g. "RDF graph" is correctly flagged as normative https://github.com/w3c/webref/blob/main/ed/dfns/rdf11-concepts.json#L330

The extraction code defaults to `normative`. Switch to `informative` requires some explicit class.

**Comment by dontcallmedom** [comment]
my bad indeed; so the problem is rather that RDF Concepts define terms that I don't think are meant to be informative in informative sections (e.g https://www.w3.org/TR/rdf11-concepts/#dfn-blank-node-identifier defined in a Note section).

this thus gets back to https://github.com/w3c/respec/issues/4295 - there probably should be a way to ignore the "informative warning" flag in respec.
