### ISSUE TITLE
Remove arguments from CSS functional selector names

### ISSUE THREAD

**Issue by cdoublev** [w3c/reffy#1145]
Would it be possible to remove any argument from the `name` of the CSS functional selectors? All are extracted without their arguments except [`::view-transition-*()`](https://github.com/w3c/webref/blob/b72dabdb9ccccd4f811047cff8722b59bdd5e656/ed/css/css-view-transitions.json#L38).

Theoretically, the name should be an identifier without the trailing parenthesis, but I think removing them would create a conflict between `:current` and `:current()`.

Below is a possible implementation as an argument of [`normalize()`](https://github.com/w3c/reffy/blob/188e5eaf59e5a235bfe33d10e0f62c1a29f099aa/src/browserlib/extract-cssdfn.mjs#L320), that should be true when the data type is `selector` (and `function`?):

```js
function normalize(value, clearFnArgs = false) {
  value = value.trim().replace(/\s+/g, ' ').replace(/−/g, '-')
  if (clearFnArgs) {
    return value.replace(/\(.+\)/, '()')
  }
  return value
}
```

**Comment by tidoust** [comment]
Yes, such selectors should have been processed as functions are. They don't match `fnRegExp` in `extractTypedDfn` because of `:` but that's an oversight. I'll fix that.
