### ISSUE TITLE
CSS `@namespace` syntax is not being extracted

### ISSUE THREAD

**Issue by OnkarRuikar** [w3c/reffy#1376]
After https://github.com/w3c/reffy/pull/1117 the syntax for `@namespace` [stopped getting properly extracted](https://github.com/w3c/webref/commit/15f0c80b0de078d46123cce51b9e2791a73ea5bd#diff-e8105ee33a37270b60ccce4b66b00de27b31f128f0d81ccf31ce216195e4b725L7). Before it was available but now it is flagged as a warning.

Do we have to modify [the syntax section in the spec's code](https://github.com/w3c/csswg-drafts/blob/195e4390c8111435a002e4c212824a320e8b817d/css-namespaces-3/Overview.bs#L150-L154)?

**Comment by tidoust** [comment]
Yes, the spec does not follow the usual pattern to define the `@namespace` at-rule. I just created https://github.com/w3c/csswg-drafts/pull/9402 to wrap the definition in `<dfn>`, which should be all that's needed for Reffy to start picking it up again.

Side note: We haven't prioritized fixing warnings in CSS extracts produced by Reffy. There may be other warnings worth fixing as well!

**Comment by OnkarRuikar** [comment]
@tidoust thanks! The [fix did it](https://github.com/w3c/webref/commit/c866f120694d0f29516790fb5efa3e7c62f8699f#diff-e8105ee33a37270b60ccce4b66b00de27b31f128f0d81ccf31ce216195e4b725).

So in order to fix `Missing definition` warning we need the term wrapped in `<dfn>`  tag. Is the location of the tag specific or anywhere on the page at least once resolves the error?

**Comment by tidoust** [comment]
Great!

> So in order to fix `Missing definition` warning we need the term wrapped in `<dfn>` tag. Is the location of the tag specific or anywhere on the page at least once resolves the error?

From a crawling perspective, the location of the `<dfn>` tag does not matter as long as it appears in a normative section of the spec. From a human perspective, the `<dfn>` tag should be where the term is actually defined.

Also, the definition must not appear *at least* once but *exactly* once. Same term must not be defined more than once in a spec in particular (unless the definitions are of different types or scoped to different namespaces).
