### ISSUE TITLE
Get rid of crawl.json

### ISSUE THREAD

**Issue by tidoust** [w3c/reffy#385]
Crawl results end up in `crawl.json`. The file is already >26MB (and yet it does not even contain raw IDL extracts). We're adding more properties to the crawl over time. For instance, we recently added definitions and targeted fragments in external documents. The list of properties should continue to grow over time, e.g. see #153.

Having one big `crawl.json` file is not fantastic. It makes it hard for humans to look for something in the file, which is often useful, especially when debugging. This includes making it hard to review diffs and spot crawl errors. Also, editing tools tend to work better with smaller JSON files. For instance, GitHub won't show the contents of the file because it is too large.

We're already producing separate CSS definitions, definitions, and IDL extract files for each spec. The idea would be to replace `crawl.json` with an index file that only contains generic information about crawled specs (metadata from w3c/browser-specs, possible error message if crawl went wrong, and links to individual files that got created during the crawl). The index file would look like:

```json
{
  "type": "crawl",
  "title": "Reffy crawl",
  "date": "2020-08-26T06:37:45.423Z",
  "options": {},
  "stats": {
    "crawled": 331,
    "errors": 0
  },
  "results": [
    {},
    {}
  ]
```

Individual results would look like:

```json
{
  "url": "https://compat.spec.whatwg.org/",
  "crawled": "https://compat.spec.whatwg.org/",
  "status": "OK",
  "seriesComposition": "full",
  "shortname": "compat",
  "series": {
    "shortname": "compat",
    "currentSpecification": "compat"
  },
  "nightly": {
    "url": "https://compat.spec.whatwg.org/",
    "repository": "https://github.com/whatwg/compat",
    "filename": "index.html"
  },
  "title": "Compatibility Standard",
  "source": "specref",
  "shortTitle": "Compatibility",
  "date": "29 June 2020",
  "generator": "bikeshed",
  "links": "links/compat.json",
  "refs": "refs/compat.json",
  "idl": "idl/compat.idl",
  "idlparsed": "idlparsed/compat.json",
  "css": "css/compat.json",
  "dfns": "dfns/compat.json",
  "headings": "headings/compat.json"
}
```

More properties may be added over time.

External projects may depend on `crawl.json`, so we may want to keep it for a while, and create a separate `index.json` file instead.

Note that, at least for now, CSS definitions and raw IDL extracts are only produced for the latest version of a spec in a series (that eases ingestion in Web Platform Tests, which follows the same model). Other files are generated per spec, not per series.

TODO:
- [x] Generate the `index.json` file at the end of the crawl (file should be ~250KB)
- [x] Generate `headings` files
- [x] Generate `idlparsed` files
- [x] Generate `links` files
- [x] Generate `refs` files
- [x] Write helper function to re-create `crawl.json` in memory from the index file (file version)
- [x] Write helper function to re-create `crawl.json` in memory from the index file (http version)
- [x] Adjust reporting tools (`merge-crawl-results` and `study-crawl`)  to use the helper function (or to use the index file directly)
- [x] Find out existing projects that use `crawl.json` and see if they can switch to `index.json`
- [x] Drop `crawl.json`

**Comment by sidvishnoi** [comment]
Would it also make sense to drop `crawl.json` from git history?

Why? The webref repo is too large. At respec.org, it takes nearly 900MB of storage (450MB if you run an aggressive git.gc, but that takes a lot of resources). `git pull` is also slow due to large repo.

Running https://github.com/github/git-sizer on webref shows:
```
➜  webref git:(master) git-sizer
Processing blobs: 51681                        
Processing trees: 12594                        
Processing commits: 3279                        
Matching commits to trees: 3279                        
Processing annotated tags: 7                        
Processing references: 40                        
| Name                         | Value     | Level of concern               |
| ---------------------------- | --------- | ------------------------------ |
| Overall repository size      |           |                                |
| * Blobs                      |           |                                |
|   * Total size               |  75.6 GiB | ********                       |
|                              |           |                                |
| Biggest objects              |           |                                |
| * Trees                      |           |                                |
|   * Maximum entries      [1] |  2.11 k   | **                             |
| * Blobs                      |           |                                |
|   * Maximum size         [2] |  46.8 MiB | ****                           |

[1]  ffc8292da7afda51a1f891b080281675369dc843 (09ab6914154ad6eaa1c3b589a88c12c940dcb8e3:ed/idlnames)
[2]  373d491dcdc010c0adad593c9960ef28469361c4 (3fb24221c8014950251c4b59233c1cb1d51c1866:ed/crawl.json)
```

Maybe creating an archived repo with crawl.json would help if people need its history or we don't want to change commit hashes with a rebase.

**Comment by tidoust** [comment]
> Would it also make sense to drop crawl.json from git history?

Totally fine with that, although I confess I don't know which Git command I should run to completely strike the file from history. Do you know?

Also, I don't know how you manage this at respec.org, but could a [shallow clone](https://www.git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt) be a possible solution not to retrieve 1GB of data?

We've started to roll out npm packages out of webref, also as a way to restrict the amount of data that one needs to import. Would a package that only includes dfns be useful for you? Or do you actually use data from other folders as well? One drawback with this approach is that we're more targeting a weekly release for these packages and dfns are the sort of things that people may be interested to see propagated as soon as possible. We can perhaps improve that... or simply create a separate repo that would only contain dfns and that would be kept in sync with the main webref repo.

@dontcallmedom Do you still need `crawl.json` somewhere? Otherwise, I believe that we should move on and drop it for good.

**Comment by dontcallmedom** [comment]
I haven't updated webidlpedia yet to not use it, but dropping it from here will be a good motivation to make it happen, so feel free to proceed whenever convenient

**Comment by sidvishnoi** [comment]
> Totally fine with that, although I confess I don't know which Git command I should run to completely strike the file from history. Do you know?

I know someone who knows: https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository#purging-a-file-from-your-repositorys-history

> Also, I don't know how you manage this at respec.org, but could a shallow clone be a possible solution not to retrieve 1GB of data?

Shallow clones when pulled often reach almost full repo size. I tried once (badly) and failed. I think a smaller repo size would benefit everyone, including faster update jobs in CI and when we want to inspect it locally.

> Would a package that only includes dfns be useful for you? [...] people may be interested to see propagated as soon as possible.

I think it could be useful, but `git pull` on the webhook update is as fast as it gets. We would also need to update the package as soon as the next one comes, so I think `git pull` is also simpler (dependabot could be haunting).

**Comment by tidoust** [comment]
> I know someone who knows: https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository#purging-a-file-from-your-repositorys-history

I gave it a try on a fork of webref now that the files are gone. That works great, reducing the size of the `.git` folder from 1GB to <50MB. However, although all commit messages are preserved, that changes all the commit ids.

Compare:
https://github.com/tidoust/webref/commits/master

... with:
https://github.com/w3c/webref/commits/master

The best is to drop local clones and clone the repo again afterwards (otherwise the local `.git` folder remains at 1GB). That's fine with me. I don't know if there can be other consequences. @dontcallmedom, @foolip, let me know if you think that's going to be a problem. In any case, I suggest to proceed after we've published this week's IDL package.

**Comment by foolip** [comment]
Rewriting the repo history is fine with me. You could preserve the original branch as a non-branch non-tag ref in the repo, so that it's not included in a clone, but is still stored by GitHub and could be retrieved later.

**Comment by tidoust** [comment]
My understanding of `git clone` was that it copied the entire history of a repo, unless you constrain it further with options such `--depth` or `--single-branch`. In other words, that you get all refs when you clone. Isn't that the case?

Practically speaking, I don't see any obvious option to preserve the original branch with the [BFG repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/). It does the magic on its own (and I don't necessarily want to learn the magic ;))

**Comment by sidvishnoi** [comment]
Might be easier to a fork this repo, archive the fork, and completely clean up this repo?

**Comment by foolip** [comment]
@tidoust there are other kinds of refs which aren't fetched by default. When you `git clone` a repo, you'll get a `.git/config` which has a section like this:
```
[remote "origin"]
	url = git@github.com:w3c/webref.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

That's saying that only `refs/heads/*` should be fetched, but one can push refs by any name, like `refs/archive/bla`.

This is very hard to discover, however, so if you push a ref like that you'll need to document it somewhere if it matters.

**Comment by tidoust** [comment]
OK, to keep things simple, I created [`w3c/webref-archive`](https://github.com/w3c/webref-archive), which now contains a clone of the `w3c/webref` repo before purning `crawl.json` files. That repository is flagged as "archived".

I then ran the BFG repo cleaner tool on `w3c/webref` to get rid of `crawl.json` files, and pushed the result, which effectively re-wrote the repo commit history. A fresh clone of `w3c/webref` is now `166MB`, the `.git` folder taking "only" `54.5MB`.

Thanks @sidvishnoi for the idea and instructions! And thanks @foolip for explaining Git internals :)

I'm closing that issue, please reopen if I missed something.
