### ISSUE TITLE
Unable to diff against published results

### ISSUE THREAD

**Issue by gsnedders** [w3c/reffy#416]
After running `npm run ed`, the following from the README fails:

> 5. **Diff with latest published version of the crawl report**: Compares the crawl results with the latest published crawl results and produce a human-readable diff in Markdown format. `generate-report reports/ed/crawl.json diff https://tidoust.github.io/reffy-reports/ed/crawl.json`

This results in:

```
TypeError: Cannot read property 'find' of undefined
```

Attaching with a debugger, this appears to be because that URL is returning an odd JSON object telling me to look at https://w3c.github.io/webref/ed/crawl.json instead.

Running `node src/cli/generate-report.js reports/ed/crawl.json diff https://w3c.github.io/webref/ed/crawl.json` instead results in:

```
TypeError: Cannot read property 'ok' of undefined
```

This happens because `generateDiffReport` ends up with `reportRef` being `undefined`, as no spec in the published `crawl.json` has a `report` property as far as I can see.

How am I meant to evaluate my changes to reffy against pre-existing data nowadays?

**Comment by tidoust** [comment]
Sorry for the bad README instructions. I just pushed an update (see https://github.com/tidoust/reffy/commit/0ef05b85369e439beaf5100ce9950c6194d927e1).

We made some changes not too long ago to deprecate `crawl.json` (the file was getting too large). The diff tool used to accept crawl reports (`crawl.json`) and anomalies reports (`study.json`) as input, and now only accepts anomalies reports.

In other words, right command should be:
```
node src/cli/generate-report.js reports/ed/study.json diff https://w3c.github.io/webref/ed/study.json
```
