### ISSUE TITLE
group which produced the document

### ISSUE THREAD

**Issue by gsnedders** [w3c/reffy#425]
It would be nice to pull out the group which produced a given document; this is information which for W3C documents is given in the "Status of this document" with e.g. "This document was produced by the CSS Working Group as a Candidate Recommendation", which is recorded in tr.rdf if not the W3C API

**Comment by tidoust** [comment]
The info should be added to the list of specs exported by browser-specs. Feature is being tracked there in https://github.com/w3c/browser-specs/issues/32

Reffy could just copy the info over once available in browser-specs.

**Comment by tidoust** [comment]
Browser-specs started to include info about groups early July and that info gets includes in crawl reports. Closing this issue accordingly.
