### ISSUE TITLE
Using Reffy as a dependency is no longer possible due to #458

### ISSUE THREAD

**Issue by pyoor** [w3c/reffy#477]
Using reffy as a dependency is no longer possible due to the changes in #458.  This is due to WebIDL2 being imported using a path relative to util.js.

https://github.com/w3c/reffy/blob/ab00f1bc152fdbb07984ffbc10cdbb75627d3b25/src/lib/util.js#L190-L192

When installed as a dependency, npm flattens module deps so that they are in the parent `node_modules`.

Note, this isn't a huge issue for me as I planned on moving away from reffy in favor of webref anyway - but I thought you should be aware in the event that you want this project to remain usable as a dependency.

**Comment by tidoust** [comment]
Thanks for the report! I had not thought about that... I'll add a conditional check to look for webidl2.
