### ISSUE TITLE
Re-assess list of well-known types for IDL parser

### ISSUE THREAD

**Issue by tidoust** [w3c/reffy#516]
See https://github.com/w3c/webref/pull/106#discussion_r578423768

**Comment by foolip** [comment]
It's possibly the list could be generated from the Web IDL spec itself, I never looked into that.

**Comment by tidoust** [comment]
I haven't tried to integrate that anywhere but as I was looking at the Web IDL spec for other reasons, I note that the following query returns the right list:

```js
[...document.querySelectorAll('[id^=idl-][data-dfn-type=interface][data-export]')]
  .map(el => Object.assign({ id: el.id, name: el.getAttribute('data-lt') ?? el.textContent }))
  .filter(el => el.name !== "DOMException" && !el.name.includes("<T>"));
```

Last filter line is needed to exclude `DOMException` (a "real" interface), `Promise`, `FrozenArray` and `ObservableArray` which are handled separately by the Web IDL parser.
