### ISSUE TITLE
Explore extraction of definitions from ECMAScript specs

### ISSUE THREAD

**Issue by tidoust** [w3c/reffy#620]
The ECMAScript specs do not follow the data definitions model that other spec support. It would be good to explore ways to extract definitions nevertheless or to improve the spec to align with the data definitions model.

**Comment by dontcallmedom** [comment]
as discussed in https://github.com/heycam/webidl/issues/1007:
* WebIDL would be a direct consumer for these definitions
* it would be best if we were to build references to the multipage version rather than the single page one

**Comment by domenic** [comment]
Streams is the other major consumer of these, due to somewhat-historical choices. (HTML would also be a major consumer but it's not anywhere near ready to use xref.)

But other specs also run into this randomly for one-off reasons, e.g. the URLPattern spec needs to do some RegExp manipulation and some discussion of Identifier syntax: https://github.com/WICG/urlpattern/blob/main/spec.bs#L28-L37

or Infra needs to do JSON manipulation: https://github.com/whatwg/infra/blob/main/infra.bs#L13-L30

**Comment by jmdyck** [comment]
What kind of definitions do you want to extract from the ES spec?

**Comment by domenic** [comment]
You can see a smattering at the links above, plus https://github.com/heycam/webidl/blob/master/index.bs#L79-L245 .

You can learn more about the definitions data model used by web platform specs at https://tabatkins.github.io/bikeshed/#dfn-contract

**Comment by dontcallmedom** [comment]
@jmdyck if it's useful, I'm happy to chat more synchronously (either IM or VC) on what this would entail.

From my quick look at the ES spec, this would be a combination of low-hanging fruits and more involved work:
* minimally, adding id attribute to existing `<dfn>` that are re-used by other specs; ideally, adding the `data-export` attribute too (although this could be done crawler-side for now)
* more involved, adding `<dfn>` to concepts that are indeed defined by the spec but not marked up as such (e.g. the concept of Array objects) - again, most usefully done starting with terms that are indeed referenced by other specs
* more involved yet (and not sure yet if useful), augmenting the [definition contract taxonomy](https://tabatkins.github.io/bikeshed/#dfn-contract) to include ES-relevant definitions types (we're discussing extracting the contract / taxonomy in a repo of its own in https://github.com/speced/spec-dfn-contract)

**Comment by dontcallmedom** [comment]
<details>
<summary>for reference, here is the list of anchors in the ES specs that are linked to from Web platform specs</summary>
  "agent"
  "agent",
  "ao-getbase",
  "ao-getreferencedname",
  "ao-hasprimitivebase",
  "ao-ispropertyreference",
  "ao-isstrictreference",
  "ao-issuperreference",
  "ao-isunresolvablereference",
  "array-exotic-objects",
  "array-index",
  "constructor",
  "current-realm"
  "current-realm",
  "early-error",
  "eqn-abs",
  "eqn-floor"
  "eqn-floor",
  "eqn-max",
  "eqn-min",
  "eqn-modulo",
  "execution-context-stack",
  "function-object",
  "global-object",
  "non-strict-function",
null
  "prod-Arguments",
  "prod-ArrowFormalParameters",
  "prod-ArrowParameters",
  "prod-AssignmentExpression",
  "prod-AsyncArrowBindingIdentifier",
  "prod-AsyncConciseBody",
  "prod-AsyncFunctionBody",
  "prod-AwaitExpression",
  "prod-BindingIdentifier",
  "prod-Block",
  "prod-CaseBlock",
  "prod-ClassElementList",
  "prod-ClassHeritage",
  "prod-ConciseBody",
  "prod-CoverCallExpressionAndAsyncArrowHead",
  "prod-CoverParenthesizedExpressionAndArrowParameterList",
  "prod-Expression",
  "prod-ForBinding",
  "prod-FunctionBody",
  "prod-GeneratorBody",
  "prod-Identifier",
  "prod-IdentifierName",
  "prod-Initializer",
  "prod-LabelIdentifier",
  "prod-LeftHandSideExpression",
  "prod-LineTerminator",
  "prod-MetaProperty",
  "prod-MethodDefinition",
  "prod-ModuleItemList",
  "prod-NumericLiteral",
  "prod-PropertyName",
  "prod-PropertySetParameterList",
  "prod-Punctuator",
  "prod-Script",
  "prod-StatementList",
  "prod-StatementListItem"
  "prod-StringLiteral",
  "prod-SuperProperty",
  "prod-Template",
  "prod-TemplateLiteral",
  "prod-UnicodeEscapeSequence",
  "prod-UniqueFormalParameters",
  "prod-VariableDeclaration",
  "prod-VariableStatement",
  "prod-YieldExpression",
  "realm"
  "realm",
  "realm-record",
  "running-execution-context",
  "script-record",
  "sec-abstract-module-records",
  "sec-agent-clusters"
  "sec-agent-clusters",
  "sec-agents",
  "sec-algorithm-conventions",
  "sec-allocatearraybuffer",
  "sec-arraybuffer-constructor",
  "sec-arraybuffer-objects",
  "sec-array-constructor"
  "sec-arraycreate",
  "sec-array-iterator-objects",
  "sec-array-objects"
  "sec-array-objects",
  "sec-array.prototype.entries",
  "sec-array.prototype.foreach",
  "sec-array.prototype.keys",
  "sec-array.prototype.map",
  "sec-array.prototype.sort",
  "sec-array.prototype.values",
  "sec-async-functions-abstract-operations-async-function-create",
  "sec-asynciterator-interface"
  "sec-asynciteratorprototype",
  "sec-block-level-function-declarations-web-legacy-compatibility-semantics",
  "sec-built-in-function-objects",
  "sec-call"
  "sec-call",
  "sec-canonicalnumericindexstring",
  "sec-code-realms"
  "sec-code-realms",
  "sec-completion",
  "sec-completion-record-specification-type",
  "sec-construct"
  "sec-construct",
  "sec-constructor",
  "sec-context-free-grammars",
  "sec-createarrayfromlist",
  "sec-createbuiltinfunction",
  "sec-createbytedatablock",
  "sec-createdataproperty",
  "sec-createdatapropertyorthrow",
  "sec-createiterresultobject",
  "sec-createmapiterator",
  "sec-createmappedargumentsobject",
  "sec-createmethodproperty"
  "sec-createmethodproperty",
  "sec-createresolvingfunctions",
  "sec-createsetiterator",
  "sec-createunmappedargumentsobject",
  "sec-cyclic-module-records"
  "sec-data-blocks",
  "sec-dataview-constructor",
  "sec-dataview-objects",
  "sec-date-constructor",
  "sec-date-objects"
  "sec-date-objects",
  "sec-definepropertyorthrow",
  "sec-detacharraybuffer",
  "sec-do-while-statement",
  "sec-ecmascript-data-types-and-values",
  "sec-ecmascript-language-lexical-grammar",
  "sec-ecmascript-language-types",
  "sec-ecmascript-language-types-bigint-type",
  "sec-ecmascript-language-types-number-type",
  "sec-ecmascript-language-types-string-type",
  "sec-environment-records",
  "sec-error-handling-and-language-extensions",
  "sec-error-objects"
  "sec-error-objects",
  "sec-for-statement",
  "sec-forward-progress"
  "sec-frompropertydescriptor",
  "sec-functionallocate",
  "sec-function-calls-runtime-semantics-evaluation",
  "sec-functioncreate",
  "sec-function-definitions-runtime-semantics-iteratorbindinginitialization",
  "sec-function-environment-records",
  "sec-generatorfunctioncreate",
  "sec-getactivescriptormodule",
  "sec-getfunctionrealm",
  "sec-getglobalobject",
  "sec-getiterator",
  "sec-getmethod",
  "sec-getmodulenamespace",
  "sec-getnewtarget",
  "sec-get-o-p"
  "sec-get-o-p",
  "sec-getprototypefromconstructor",
  "sec-getsuperconstructor",
  "sec-getthisenvironment",
  "sec-getthisvalue",
  "sec-getvaluefrombuffer",
  "sec-globaldeclarationinstantiation",
  "sec-hasownproperty",
  "sec-hostensurecancompilestrings",
  "sec-hostresolveimportedmodule",
  "sec-ifabruptrejectpromise",
  "sec-immutable-prototype-exotic-objects",
  "sec-isaccessordescriptor",
  "sec-isanonymousfunctiondefinition",
  "sec-isarray",
  "sec-iscallable",
  "sec-isconstructor"
  "sec-isconstructor",
  "sec-isdatadescriptor",
  "sec-isdetachedbuffer"
  "sec-isdetachedbuffer",
  "sec-isinteger",
  "sec-ispropertykey",
  "sec-issharedarraybuffer",
  "sec-iterable-interface",
  "sec-iterabletolist",
  "sec-%iteratorprototype%-object",
  "sec-iteratorstep",
  "sec-iteratorvalue",
  "sec-json.parse",
  "sec-json.stringify",
  "sec-lexical-environments",
  "sec-list-and-record-specification-type"
  "sec-list-and-record-specification-type",
  "sec-literals-numeric-literals",
  "sec-makebasicobject",
  "sec-makeclassconstructor",
  "sec-makeconstructor",
  "sec-makemethod",
  "sec-map-objects",
  "sec-nativeerror-object-structure",
  "sec-native-error-types-used-in-this-standard-rangeerror",
  "sec-native-error-types-used-in-this-standard-syntaxerror",
  "sec-native-error-types-used-in-this-standard-typeerror"
  "sec-native-error-types-used-in-this-standard-typeerror",
  "sec-newdeclarativeenvironment",
  "sec-newfunctionenvironment",
  "sec-newmoduleenvironment",
  "sec-newpromisecapability",
  "sec-normalcompletion",
  "sec-numbertorawbytes",
  "sec-objectcreate",
  "sec-object.freeze"
  "sec-object-internal-methods-and-internal-slots"
  "sec-object-internal-methods-and-internal-slots",
  "sec-object-objects",
  "sec-ordinarycallbindthis",
  "sec-ordinarycallevaluatebody",
  "sec-ordinarycreatefromconstructor",
  "sec-ordinarydefineownproperty",
  "sec-ordinarygetownproperty",
  "sec-ordinaryobjectcreate"
  "sec-ordinaryobjectcreate",
  "sec-ordinary-object-internal-methods-and-internal-slots"
  "sec-ordinary-object-internal-methods-and-internal-slots",
  "sec-ordinarysetwithowndescriptor",
  "sec-own-property"
  "sec-own-property",
  "sec-parsefloat-string"
  "sec-parseint-string-radix",
  "sec-performeval",
  "sec-performeval-rules-outside-constructors",
  "sec-performeval-rules-outside-functions",
  "sec-performeval-rules-outside-methods",
  "sec-performpromisethen",
  "sec-prepareforordinarycall",
  "sec-promise.all",
  "sec-promisecapability-records",
  "sec-promise-constructor",
  "sec-promise-objects"
  "sec-promise-objects",
  "sec-promise.prototype.then",
  "sec-promise.reject",
  "sec-promise-resolve",
  "sec-properties-of-generator-prototype",
  "sec-properties-of-the-array-prototype-object",
  "sec-properties-of-the-error-prototype-object",
  "sec-properties-of-the-function-prototype-object",
  "sec-properties-of-the-object-prototype-object",
  "sec-property-attributes",
  "sec-property-descriptor-specification-type",
  "sec-proxycreate",
  "sec-proxy-object-internal-methods-and-internal-slots",
  "sec-reference-specification-type"
  "sec-regexp-regular-expression-objects"
  "sec-requireobjectcoercible",
  "sec-resolvebinding",
  "sec-returnifabrupt",
  "sec-returnifabrupt-shorthands"
  "sec-returnifabrupt-shorthands",
  "sec-samevalue",
  "sec-samevaluezero",
  "sec-setfunctionlength",
  "sec-setfunctionname",
  "sec-set-immutable-prototype",
  "sec-setintegritylevel",
  "sec-set-objects",
  "sec-set-o-p-v-throw",
  "sec-setvalueinbuffer",
  "sec-sharedarraybuffer-objects",
  "sec-strict-mode-code",
  "sec-string-constructor",
  "sec-terms-and-definitions-function",
  "sec-terms-and-definitions-number-type",
  "sec-terms-and-definitions-string-type",
  "sec-throwcompletion",
  "sec-time-values-and-time-range"
  "sec-tobigint",
  "sec-tobigint64",
  "sec-toboolean"
  "sec-toboolean",
  "sec-toint32",
  "sec-tolength",
  "sec-tonumber",
  "sec-tonumeric",
  "sec-toobject",
  "sec-topropertydescriptor",
  "sec-tostring"
  "sec-tostring",
  "sec-touint32",
  "sec-typedarray-constructors"
  "sec-typedarray-objects",
  "sec-types-of-source-code",
  "sec-utf16encoding",
  "sec-variablestatements-in-catch-blocks",
  "sec-web-compat-evaldeclarationinstantiation",
  "sec-web-compat-functiondeclarationinstantiation",
  "sec-well-known-symbols",
  "strict-function",
  "super-reference",
  "surrounding-agent"
  "surrounding-agent",
  "table-the-typedarray-constructors"
</details>

(extracted from https://github.com/w3c/webref/tree/master/ed/links with `jq '.links["https://tc39.github.io/ecma262/"]' *.json |sort|uniq`

**Comment by jmdyck** [comment]
If you'd like to see those kinds of changes to the ES spec, you should probably first get buy-in from the editors.
