### ISSUE TITLE
Support new types 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/reffy#719]
It would be great to support dfn-type:

 * task-source - https://github.com/w3c/respec/pull/3728 
 * permission - https://github.com/w3c/respec/pull/3729

**Comment by marcoscaceres** [comment]
After yesterday's discussion, and based on some other related issues, I've decided that "task-source" can just continue to be a concept. 

I think I was trying to solve this the wrong way... the problem I've been trying to solve is easily finding task sources across specs. Giving them a type was a quick way to solve that, but at the cost of adding a new type to the system... what I actually need to improve is the search at https://respec.org/xref/ to find them. 

I'm going to think more about "permission" as type too... I think permission might be adequate as a type, as permissions do have a particular meaning and special functionality in the platform.

**Comment by dontcallmedom** [comment]
support for permission type has been added
