### ISSUE TITLE
Invalid definition of CSS `<step-easing-function>` 

### ISSUE THREAD

**Issue by cdoublev** [w3c/reffy#983]
`step-start | step-end | steps(<integer>[, <step-position>]?) <step-position>` is extracted from [CSS Easing 2](https://drafts.csswg.org/css-easing-2/#typedef-step-easing-function) as the definition of `<step-easing-function>` in `w3c/webref`, but it can be read as the same value definition but without the trailing `<step-position>`, which seems to be consumed in the next definition (of `<step-position>`).

~~I believe the trailing `<step-position>` has appeared because of [this recent change (3 hours ago)](https://github.com/w3c/csswg-drafts/commit/d78f00ef1ebaa3fd425a1298f8beb05b801541e0#diff-ca927dd29cb6ca601ab2e41a29edcee2c37ee0bf5afaa93f2dbcbf8a55b79c86L246). Can you handle this definition without the wrapping `<div>` or should I report the issue on `w3c/csswg-drafts`?~~

The trailing `<step-position>` has appeared in [this commit (4 days ago)](https://github.com/w3c/webref/commit/08f9281e5f74d6f8354c31d0b9177fb0ddd6b29a) but I do not know if the issue comes from Bikeshed or Reffy. The last two changes in the source are from 3 hours ago and February.

**Comment by tidoust** [comment]
I'll look into it. I think Reffy gets confused because the spec's markup is a bit clumsy there (the two definitions are enclosed in a `<div>`, the first one directly appears under it, the second one has a wrapping `<p>`).

**Comment by tidoust** [comment]
Not sure what happened, but the update made to the Editor's Draft fixed the problem. Fix to be released in next version of `@webref/css` later this week.

**Comment by cdoublev** [comment]
It is [back](https://github.com/w3c/webref/commit/761040dc0a770855c174ff2f2fb61d02fe4677ed#diff-e8132bc431bb226e7460d7268f861faf64598154a728982e294539d8455199a1)! ^_^

**Comment by cdoublev** [comment]
I believe that it should be fixed in Bikeshed but the following untested change [there](https://github.com/w3c/reffy/blob/60e83395b708eadb8a174a31f8a1ba0e08ca85b6/src/browserlib/extract-cssdfn.mjs#L247) can be a workaround:

```diff
  if (text.match(/\s?=\s/)) {
+   const productions = []
+   let production = ''
+   const parts = text.split(/(\n|=)/)
+   for (const [index, part] of parts.entries()) {
+     if (part === '\n' && parts[index + 2] === '=') {
+       productions.push(production.trim())
+       production = ''
+     } else {
+       production += part
+     }
+   }
+   productions.push(production.trim())
+   productions.forEach(text => {  
       // Definition appears in a "prod = foo" text, that's all good
       parseProductionRule(text, { pureSyntax: true });
+    }
  }
```

**Comment by tidoust** [comment]
Many thanks for the code input! I took a similar but slightly different approach to make that part of the logic more resilient to the many ways CSS specs present and combine production rules!
