### ISSUE TITLE
Invalid definition of CSS `<snap-block()>` and `<snap-inline()>`

### ISSUE THREAD

**Issue by cdoublev** [w3c/reffy#984]
Can you please tell me if you would be able to parse the definitions of [`<snap-block()>`](https://drafts.csswg.org/css-page-floats-3/#funcdef-float-snap-block) and [`<snap-inline()>`](https://drafts.csswg.org/css-page-floats-3/#funcdef-float-snap-inline) so that they are `snap-block( <length> , [ start | end | near ]? )` and `snap-inline( <length> , [ left | right | near ]? )`, respectively, or if I should request for a proper value definition block (below the `float` property definition table) on `w3c/csswg-drafts`?

**Comment by tidoust** [comment]
Ah, good catch. No need to change the spec, they should have been extracted. That's a bug in the extraction logic, the following RegExp should only match functions defined with parameters (right now, it matches `snap-block()` and thus code thinks it has the right expanded form and does not look into `<dd>`:
https://github.com/w3c/reffy/blob/9f3b6884e356652b1356bb6c7346965f87982c4d/src/browserlib/extract-cssdfn.mjs#L232
